services:
  # launch a Linux command line
  sh: # docker-compose run --rm sh
    image: physino/root
    command: /usr/bin/bash
    environment: # https://docs.docker.com/desktop/networking
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/root/dukecevns
    working_dir: /root/dukecevns

